### PR TITLE
 Add firmware 1.24 for 362001065279

### PR DESCRIPTION
**Pull request by wangeris**
new version firmware 1.23 available from EU servers for 362001065279

### CODE REVIEW

**Comment by wangeris** [comment]
if this is acceptable, there seems to be v1.24 on http://test.grih.gree.com/wifiModule/Lastversion?firmwareCode=362001065279 which i can submit a pull request for too

**Comment by mkaluza** [comment]
already waiting https://github.com/maxim-smirnov/gree-wifimodule-firmware/pull/8

btw your .md file looks off

Though I haven't seen 1.24 yet, nice

**Comment by wangeris** [comment]
> already waiting #8

sorry didnr realize you did it first, I can remove this pull

fixed the md file too

**Comment by mkaluza** [comment]
no, that's fine, just update the title to 1.24 :)
mine contains 22,23 and 25

**Pull request merged**
